Models/Admin.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Project_Group3.Models
{
    public partial class Admin
    {
        public string AdminId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Models/Category.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Project_Group3.Models
{
    public partial class Category
    {
        public Category()
        {
            Courses = new HashSet<Course>();
        }

        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Course> Courses { get; set; }
    }
}

Models/Course.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Project_Group3.Models
{
    public partial class Course
    {
        public string CourseId { get; set; }
        public string CourseName { get; set; }
        public string Description { get; set; }
        public string CategoryId { get; set; }
        public string Picture { get; set; }
        public int? TotalTime { get; set; }
        public decimal? Price { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Status { get; set; }

        public virtual Category Category { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Project_Group3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Instructor.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Project_Group3.Models
{
    public partial class Instructor
    {
        public string InstructorId { get; set; }
        public decimal? Income { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public DateTime? Birthday { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public int? Status { get; set; }
    }
}

Models/Learner.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Project_Group3.Models
{
    public partial class Learner
    {
        public string LearnerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public DateTime? Birthday { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public decimal? Wallet { get; set; }
        public int? Status { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Project_Group3.Models;

namespace Project_Group3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Project_Group3.DAO;
using Project_Group3.Models;

namespace Project_Group3.Controllers
{
    public class InstructorController : Controller
    {
        public IActionResult Index()
        {
            var instructorList = InstructorDAO.Instance.GetInstructorlist();
            return View(instructorList);
        }

        public IActionResult Detail(string instructorID)
        {
            instructorID = "1";
            if (string.IsNullOrEmpty(instructorID))
            {
                return NotFound();
            }

            var instructor = InstructorDAO.Instance.GetInstructorByID(instructorID);

            if (instructor == null)
            {
                return NotFound();
            }

            return View(instructor);
        }

        public ActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Instructor instructor){
            try{
                if(ModelState.IsValid){
                    InstructorDAO.Instance.AddNew(instructor);
                }
                return RedirectToAction(nameof(Index));
            }catch(Exception ex){
                ViewBag.Message = ex.Message;
                return View(instructor);
            }
        }

        public IActionResult Edit(string instructorID)
        {
            instructorID = "1";
            if(string.IsNullOrEmpty(instructorID)){
                return NotFound();
            }
            var instructor = InstructorDAO.Instance.GetInstructorByID(instructorID);
            if(instructor == null){
                return NotFound();
            }
            return View(instructor);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string instructorID, Instructor ins){
            try{
                if(id != car.CarId){
                    return NotFound();
                }
                if(ModelState.IsValid){
                    carRepository.UpdateCar(car);
                }
                return RedirectToAction(nameof(Index));
            }catch(Exception ex){
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Instructor/Create.cshtml
@model Project_Group3.Models.Instructor

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/fonts/boxicons.css" />

<div class="container-fluid mt-2 mb-3 p-0">
    <div class="card mb-4 bg-theme">
        <form asp-action="Create" class="ml-5 mt-3 mb-3">
            <div class="container-fluid">
                <div class="row">
                    <h1 class="text-theme">@ViewBag.Message</h1>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="InstructorId" class="text-theme font-weight-bold"></label>
                            <input asp-for="InstructorId" class="form-control" style="width: 80%;"/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="FirstName" class="text-theme font-weight-bold"></label>
                            <input asp-for="FirstName" class="form-control" style="width: 80%;"/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="LastName" class="text-theme font-weight-bold"></label>
                            <input asp-for="LastName" class="form-control" style="width: 80%;"/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Gender" class="text-theme font-weight-bold"></label>
                            <select asp-for="Gender" class="form-control" style="width: 80%;"/>
                                <option value="">Please select...</option>
                                <option value="Nam">Nam</option>
                                <option value="Nữ">Nữ</option>
                                <option value="Khác">Khác</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="text-theme font-weight-bold"></label>
                            <input asp-for="PhoneNumber" class="form-control" style="width: 80%;"/>
                        </div>
                    </div>
                    @* <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="DateOfBirth" class="text-theme font-weight-bold"></label>
                            <input asp-for="DateOfBirth" class="form-control" style="width: 80%;"/>
                        </div>
                    </div> *@
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Email" class="text-theme font-weight-bold"></label>
                            <input asp-for="Email" class="form-control" style="width: 80%;"/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Country" class="text-theme font-weight-bold"></label>
                            <select asp-for="Country" class="form-control" style="width: 80%;"/>
                                <option value="">Please select...</option>
                                <option value="Vietnam">Vietnam</option>
                                <option value="Japan">Japan</option>
                                <option value="America">America</option>
                                <option value="England">England</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Username" class="text-theme font-weight-bold"></label>
                            <input asp-for="Username" class="form-control" style="width: 80%;"/>
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Password" class="text-theme font-weight-bold"></label>
                            <input asp-for="Password" class="form-control" style="width: 80%;"/>
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-success mr-3">Create</button>
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>

@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

Views/Instructor/Detail.cshtml
@model Project_Group3.Models.Instructor
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/fonts/boxicons.css" />

<div class="container-fluid mt-2 mb-3 p-0">
    <div class="card mb-4 bg-theme">
        <div class="card-body d-flex" style="justify-content: space-between;">
            <div class="d-flex align-items-start align-items-sm-center gap-4 ml-5">
                <div class="avatar-user mr-2 mt-5">
                    @* @if(@Model.Picture.Length != 0){
                        <img class="avatar-initial rounded-circle bg-label-warning" src="@Url.Content(@Model.Picture)">
                    }else{
                    } *@
                        <img class="avatar-initial rounded-circle bg-label-warning" src="~/img/1.png">
                </div>
                <div class="id-text form-group ml-2">
                    <label asp-for="InstructorId" class="text-theme font-weight-bold"></label>
                    <input value="@Model.InstructorId" class="form-control" style="width: 80%;" disabled/>
                </div>
                <div class="btn-next mt-5 d-flex" >
                    <form method="post" action="/Instructor/Previous">
                        <input type="hidden" name="InstructorId" value="@Model.InstructorId" />
                        <button type="submit" class="btn btn-primary text-white"><i class='bx bx-left-arrow-alt'></i></button>
                    </form>
                    <form class="ml-3" method="post" action="/Instructor/Next">
                        <input type="hidden" name="InstructorId" value="@Model.InstructorId" />
                        <button type="submit" class="btn btn-primary text-white"><i class='bx bx-right-arrow-alt'></i></button>
                    </form> 
                </div>
            </div>
        </div>
        <form asp-action="Edit" method="post" class="mb-5">
            <div class="container-fluid ml-5">
                <div class="row">
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="FirstName" class="text-theme font-weight-bold"></label>
                            <input value="@Model.FirstName" class="form-control" style="width: 80%;" disabled/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="LastName" class="text-theme font-weight-bold"></label>
                            <input value="@Model.LastName" class="form-control" style="width: 80%;" disabled/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Gender" class="text-theme font-weight-bold"></label>
                            <input value="@Model.Gender" class="form-control" style="width: 80%;" disabled/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Birthday" class="text-theme font-weight-bold"></label>
                            <input class="form-control" value="@Model.Birthday" style="width: 80%;" disabled/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Email" class="text-theme font-weight-bold"></label>
                            <input value="@Model.Email" class="form-control" style="width: 80%;" disabled/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Country" class="text-theme font-weight-bold"></label>
                            <input value="@Model.Country" class="form-control" style="width: 80%;" disabled/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="Username" class="text-theme font-weight-bold"></label>
                            <input value="@Model.Username" class="form-control" style="width: 80%;" disabled/>
                        </div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="text-theme font-weight-bold"></label>
                            <input value="@Model.PhoneNumber" class="form-control" style="width: 80%;" disabled/>
                        </div>
                    </div>
                </div>
            </div>
            <a asp-action="Index" class="btn btn-secondary ml-5" style="width: 10rem;">Back</a>
        </form>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="~/icon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body onload="time()">
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 text-white bg-theme p-0" style="min-height: 750px;">
                <a href="#" class="app-brand text-decoration-none d-block mt-3 mb-3 ml-4">
                    <h2 class="m-0 fw-bold"><span class="text-primary">W3</span>COURSE</h2>
                </a>
                <ul class="navbar-nav flex-grow-1 ml-2">
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Home" asp-action="Index">
                            <i class="menu-icon tf-icons bx bx-home-circle"></i>
                            Dashboards</a>
                    </li>
                    <li class="menu-header small text-uppercase mt-2">
                        <span class="menu-header-text text-theme">Apps &amp; Pages</span>
                    </li>
                    <li class="nav-item pl-3 active">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Instructor" asp-action="Index">
                            <i class="menu-icon tf-icons bx bx-user-voice"></i>
                            Instructor</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Learner" asp-action="Index">
                            <i class="menu-icon tf-icons bx bx-group"></i>
                            Learner</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Home" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-book"></i>
                            Course</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-bell"></i>
                            Notification</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Transaction" asp-action="Index">
                            <i class="menu-icon tf-icons bx bx-wallet"></i>
                            Transaction</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-envelope"></i>
                            Email</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-chat"></i>
                            Chat</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-calendar"></i>
                            Calendar</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-grid"></i>
                            Kanban</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
                            Authentications</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
                            Change Password</a>
                    </li>
                    <li class="menu-header small text-uppercase mt-2">
                        <span class="menu-header-text text-theme">Other &amp; Pages</span>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-support"></i>
                            Support</a>
                    </li>
                    <li class="nav-item pl-3">
                        <a class="nav-link text-theme" asp-area="" asp-controller="Admin" asp-action="Privacy">
                            <i class="menu-icon tf-icons bx bx-cog"></i>
                            Setting</a>
                    </li>
                </ul>
            </div>
            <div class="col-10 p-0 layout-theme text-white">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 p-0" style="min-height: 90px;">
                            <nav class="navbar navbar-expand-sm navbar-dark bg-theme pt-2 pb-3">
                                <div class="container-fluid bg-theme mt-3 ml-5">
                                    <h5 class="card-title mb-0 text-theme">List of @ViewData["Title"]</h5>
                                    
                                    <ul class="navbar-nav flex-row align-items-center ms-auto">
                                        <li class="nav-item ">
                                            <div id="clock" class="text-theme"></div>
                                        </li>
                                        <li class="nav-item ml-3">
                                            <a href="#" class="icon-taskbar theme-toggle">
                                                <i class='bx bx-sun text-theme' title="Light Mode"></i>
                                                <i class='bx bx-moon text-theme'title="Dark Mode"></i>
                                            </a>
                                        </li>
                                        <li class="nav-item ml-3">
                                            <a class="notifi-icon">
                                                <i class="tf-icons bx bx-bell text-theme"></i>
                                                <div class="badge bg-danger rounded-pill">5</div>
                                            </a>
                                        </li>
                                        <li class="nav-item ml-3">
                                            <div class="avatar-admin mr-2">
                                                <img class="avatar-initial rounded-circle bg-label-warning" src="~/img/1.png">
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                        <div class="col-lg-12 text-white p-0 mb-4">
                            <div class="container-fluid">
                                <main role="main" class="pb-3">
                                    @RenderBody()
                                </main>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>